apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: minio