# for icon
# https://gethomepage.dev/configs/services/#descriptions 
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.10.9
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Overseerr:
                href: https://overseerr.qos.cc/
                description: Moive and TV management
                icon: overseerr.svg
            - Github:
                href: https://www.github.com
                icon: github.svg
            - Gitea:
                href: https://git.qos.cc
                description: Git forge
                icon: gitea.svg
            - Immich:
                href: https://photos.qos.cc
                description: photos management
                icon: sh-immich.svg
          - Management:
            - Radarr:
                href: https://radarr.qos.cc
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.qos.cc
                description: TV show manager
                icon: sonarr.svg
            - qBittorrent:
                href: http://172.23.31.36:8090/
                description: qBittorrent client
                icon: qbittorrent.svg
            - Kanidm:
                href: https://auth.qos.cc
                description: Identity management
                icon: https://auth.qos.cc/pkg/img/logo-square.svg
          - Development:
            - Woodpecker:
                href: https://ci.ret0.dev
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.qos.cc
                description: Continuous deployment
                icon: argocd.svg
            - Grafana:
                href: https://grafana.ret0.dev
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Speedtest:
                href: https://speedtest.qos.cc
                description: Internal network speed test
                icon: openspeedtest.png
            - Node-red:
                href: https://node-red.qos.cc
                description: Node for homeassist
                icon: node-red.svg
            - Stiring PDF:
                href: https://pdf.qos.cc/
                description: A pdf utils
                icon: sh-stirling-pdf.svg
        bookmarks.yaml: |
          - Infrastructure:
            - Router:
              - href: http://172.23.31.99
                icon: router.svg
            - Unifi:
              - href: https://unifi.qos.cc
                icon: unifi.svg
            - Home Assistant:
              - href: https://ha.qos.cc
                icon: home-assistant.svg
            - Proxmox:
              - href: https://pve.qos.cc
                icon: proxmox.svg
            - TrueNAS:
              - href: https://nas.qos.cc
                icon: truenas.svg
          - AI services:
            - ChatGPT:
              - href: https://chat.openai.com
            - Claude:
              - href: https://claude.ai
            - Perplexity:
              - href: https://www.perplexity.ai
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
            - Zerotier:
              - href: https://my.zerotier.com
                icon: zerotier.svg
