plex:
  image:
    tag: 1.40.1.8227-c0dd5a73e
  env:
    TZ: Asia/Shanghai
    PLEX_CLAIM: "claim-h2d1n44d-zWzfxAh8TUm" # https://www.plex.tv/claim 首次使用时填写这个 env 可直接通过域名来访问，否则需要端口转发。
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host plex.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  persistence:
    config:
      enabled: true
      mountPath: /config
      existingClaim: config
    media:
      enabled: true
      mountPath: /media
      existingClaim: media
  resources:
    limits:
      gpu.intel.com/i915: 1

