plex:
  env:
    PUID: 2199
    PGID: 568
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'true'
        hajimari.io/icon: 'plex'
      hosts:
        - host: &host plex.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
      retain: true
    media:
      enabled: true
      mountPath: /media
      existingClaim: media
