plex:
  env:
    TZ: Asia/Shanghai
    # PLEX_CLAIM: "" https://www.plex.tv/claim 首次使用时填写这个 env 可直接通过域名来访问，否则需要端口转发。
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/icon: "plex"
        hajimari.io/appName: "plex"
      hosts:
        - host: &host plex.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
  persistence:
    config:
      enabled: true
      mountPath: /config
      existingClaim: config
    media:
      enabled: true
      mountPath: /media
      existingClaim: media
  # resources:
  #   limits:
  #     gpu.intel.com/i915: 1

