app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: frooodle/s-pdf
            tag: 0.22.8
          env:
            TZ: Asia/Shanghai
            DOCKER_ENABLE_SECURITY: false
  service:
    main:
      controller: main
      ports:
        http:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host pdf.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: pdf-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "truenas-iscsi-csi"
      size: 10Gi
      globalMounts:
        - path: /configs
    training-data:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "truenas-iscsi-csi"
      size: 10Gi
      globalMounts:
        - path: /usr/share/tessdata
