vaultwarden:
  image:
    tag: "1.30.3-alpine"
  ingress:
    enabled: true
    hostname: "pwd.qos.cc" 
    tlsSecret: "vaultwarden-tls-certificate"
    additionalAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  # TODO: reference hostname
  domain: https://pwd.qos.cc
  signupsAllowed: false
  adminToken:
    existingSecret: "secret"
    existingSecretKey: "admin_token"
  database:
    type: "postgresql"
    existingSecret: "secret"
    existingSecretKey: "database_uri"
  data:
    name: "data"
    size: "10Gi"
    class: ""
    path: "/data"
    keepPvc: true
  webVaultEnabled: "false"
  timeZone: "Asia/Shanghai"
  pushNotifications:
    installationId: 33d7b87c-cdcd-43e6-9c8e-b14700c761af
    installationKey: Xh98P2Lhdi6Hhsl8QI4C
