vaultwarden:
  ingress:
    enabled: true
    class: "nginx"
    hostname: &host "pwd.ret0.dev" 
    tlsSecret: "vaultwarden-tls-certificate"
    additionalAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  signupsAllowed: false
  smtp:

    enabled: false
    host: mx01.ret0.dev
    from: no-reply@ret0.dev
    fromName: "Vault Administrator"
    username:
      value: admin
    password: 
      value: password #just make it running.
  domain: https://pwd.ret0.dev
  adminToken:
    existingSecret: "secret"
    existingSecretKey: "admin_token"
  database:
    type: "postgresql"
    existingSecret: "secret"
    existingSecretKey: "database_uri"
  storage:
    enabled: true
    size: "3Gi"
    class: "standard-rwo"
