jackett:
  env:
    TZ: Asia/Shanghai
    PUID: 2199
    PGID: 568
  image:
    repository: ghcr.io/linuxserver/jackett
    pullPolicy: IfNotPresent
    tag: 0.21.1056
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host jackett.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jackett-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      subPath: movie_tools/jackett
      existingClaim: jackett-config
      retain: true

flaresolverr:
  env:
    TZ: Asia/Shanghai
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    pullPolicy: IfNotPresent
    tag: v3.3.6