app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 568
  controllers:
    main:
      containers:
        main:
          image:
            repository: linuxserver/jackett
            tag: 0.21.2358
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
  service:
    main:
      controller: main
      ports:
        http:
          port: 9117
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host jackett.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: jackett-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      globalMounts:
        - path: /config
