jackett:
  image:
    repository: ghcr.io/linuxserver/jackett
    pullPolicy: IfNotPresent
    tag: 0.20.3288
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host jackett.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jackett-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
      retain: true