jackett:
  image:
    repository: tccr.io/truecharts/jackett
    pullPolicy: IfNotPresent
    tag: 0.20.2297@sha256:4de1541011cb56935ba5a8e28a58f6cbcf62a903393dc94581eda0b6e2aa117c
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host jackett.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jackett-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
      retain: true