apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: admin_token
      remoteRef:
        key: vaultwarden.admin
        property: token
    - secretKey: database_uri
      remoteRef:
        key: vaultwarden.database
        property: uri
