apiVersion: v2
name: database
version: 0.0.0
dependencies:
- name: postgresql
  version: 15.5.16
  repository: https://charts.bitnami.com/bitnami
- name: mysql
  version: 11.1.9
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 20.0.1
  repository: https://charts.bitnami.com/bitnami
