apiVersion: v2
name: database
version: 0.0.0
dependencies:
- name: postgresql
  version: 14.2.3
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 18.17.0
  repository: https://charts.bitnami.com/bitnami
