apiVersion: v2
name: database
version: 0.0.0
dependencies:
- name: postgresql
  version: 13.2.28
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 18.6.3
  repository: https://charts.bitnami.com/bitnami
