apiVersion: v2
name: database
version: 0.0.0
dependencies:
- name: postgresql
  version: 14.3.1
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 18.19.1
  repository: https://charts.bitnami.com/bitnami
