apiVersion: v2
name: database
version: 0.0.0
dependencies:
- name: postgresql
  version: 15.4.0
  repository: https://charts.bitnami.com/bitnami
- name: mysql
  version: 11.0.0
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 19.5.0
  repository: https://charts.bitnami.com/bitnami
