postgresql:
  global:
    storageClass: "longhorn"
    postgresql:
      auth:
        postgresPassword: "amaretto-snowplow-reps"
  primary:
    name: primary 
    service:
      type: LoadBalancer
redis:
  architecture: standalone
  auth:
    enabled: false
  persistence:
    storageClass: "longhorn"