postgresql:
  global:
    storageClass: "longhorn"
    postgresql:
      auth:
        existingSecret: postgresql-auth
        secretKeys:
          adminPasswordKey: "adminPassword"
  primary:
    name: primary 
    service:
      type: LoadBalancer
    persistence:
      existingClaim: data
      subPath: postgresql
redis:
  architecture: standalone
  auth:
    enabled: false
  persistence:
    existingClaim: data
    subPath: redis