postgresql:
  image:
    registry: ghcr.io
    repository: retx0/bitnami-postgresql
  global:
    postgresql:
      auth:
        existingSecret: postgresql-auth
        secretKeys:
          adminPasswordKey: "adminPassword"
  primary:
    name: primary 
    resourcesPreset: none
    service:
      type: LoadBalancer
    persistence:
      existingClaim: data
      subPath: postgresql
mysql:
  auth:
    existingSecret: mysql-auth
  primary:
    name: primary 
    resourcesPreset: none
    service:
      type: LoadBalancer
    persistence:
      existingClaim: data
      subPath: mysql
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      existingClaim: data
      subPath: redis