apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-movie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: nfs-movie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subfinder-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi