app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 568
  controllers:
    main:
      containers:
        main:
          image:
            repository: emby/embyserver
            tag: 4.9.0.11
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
  service:
    main:
      controller: main
      ports:
        http:
          port: 8096
          protocol: HTTP
  ingress:
    main:
      enabled: false
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host emby.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: emby-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      globalMounts:
        - path: /config
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/nfs/pt
      globalMounts:
        - path: /media
