app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 568
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0300_8086.present
              operator: In
              values: [ "true" ]
  controllers:
    main:
      containers:
        main:
          image:
            repository: emby/embyserver
            tag: 4.9.0.15
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 8096
          protocol: HTTP
  ingress:
    main:
      enabled: false
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host emby.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: emby-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      globalMounts:
        - path: /config
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/nfs/pt
      globalMounts:
        - path: /media
