n8n:
  domain: n8n.ret0.dev
  existingSecret: n8n-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host n8n.ret0.dev
        paths:
          - /
    tls:
      - secretName: n8n-tls-certificate
        hosts:
          - *host
  config:
    database:
      type: postgresdb
      postgresdb:
        host: database-postgresql.database.svc.cluster.local
        user: "n8n"
    generic:
      timezone: "Asia/Shanghai"
    host: *host
  extraEnv:
    WEBHOOK_URL: "https://n8n.ret0.dev"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2G