n8n:
  existingSecret: n8n-config
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/icon: "puzzle"
    hosts:
      - host: &host n8n.qos.cc
        paths:
          - /
    tls:
      - secretName: n8n-tls-certificate
        hosts:
          - *host
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2G
    storageClass: longhorn