n8n:
  config:
    database:
      type: 'postgresdb'
      host: database-postgresql.database.svc.cluster.local
      user: n8n
    generic:
      timezone: "Asia/Shanghai"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/icon: "puzzle"
    hosts:
      - host: &host double-take.qos.cc
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: double-take-tls-certificate
        hosts:
          - *host
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2G
    storageClass: longhorn