freshrss:
  env:
    TZ: "Asia/Shanghai"
  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host rss.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: rss-tls-certificate
          hosts:
            - *host

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: longhorn
