unifi:
  image:
    tag: "7.3"
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/icon: "router-network"
        hajimari.io/appName: "unifi"
      hosts:
        - host: &host unifi.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: unifi-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      existingClaim: config
video:
  ingress:
    enabled: true


