unifi:
  image: 
    repository: ghcr.io/jacobalberty/unifi-docker
    tag: v8.0.28
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host unifi.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: unifi-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      existingClaim: config
video:
  ingress:
    enabled: true


