apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.23.29.4
    path: "/mnt/wd-disk/frigate"
  mountOptions:
    - nfsvers=4.2