apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-recording
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  resources:
    requests:
      storage: 350Gi
  volumeName: video-recording