apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-frigate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Gi
  volumeName: nfs-frigate