app-template:
  controllers:
    main:
      containers:
        init-container:
          image: 
            repository: busybox
            tag: "1.36.1"
          command: ['/bin/sh', '/scripts/setup-env.sh']
        xiaoya:
          image:
            repository: xiaoyaliu/alist
            tag: "latest"
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host xiaoya.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: xiaoya-tls-certificate
  persistence:
    config:
      enabled: true
      existingClaim: pvc-config
      globalMounts:
        - path: /data/
          subPath: xiaoya
    env-script:
      enabled: true
      type: configMap
      name: scripts
      advancedMounts:
        main:
          init-container:
            - path: /scripts
