app-template:
  controllers:
    main:
      nameOverride: alist
      containers:
        init-container:
          image: 
            repository: busybox
            tag: "1.36.1"
          command: ['/bin/sh', '/scripts/setup-env.sh']
          envFrom: 
            - secret: xiaoya-token
        xiaoya:
          dependsOn:
            - init-container
          image:
            repository: xiaoyaliu/alist
            tag: "latest"
            pullPolicy: Always
          probes:
            liveness:
              spec:
                initialDelaySeconds: 500
    update:
      type: cronjob
      cronjob:
        timeZone: Asia/Shanghai
        schedule: 0 2 */9 * *
      containers:
        glue:
          image:
            repository: xiaoyaliu/glue
            tag: latest
            pullPolicy: Always
          command: ['/update.sh']
          env:
            LANG: C.UTF-8
    clean:
      type: cronjob
      cronjob:
        timeZone: Asia/Shanghai
        schedule: 0 3 * * *
      containers:
        glue:
          image:
            repository: curlimages/curl
            tag: 8.6.0
          command: ['/bin/sh', '-c']
          args:
              - sh <(curl -s https://git.qos.cc/public/aliyun_clear/raw/branch/main/clear.sh)
          env:
            LANG: C.UTF-8
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host xiaoya.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: xiaoya-tls-certificate
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Mi
      storageClass: longhorn
      retain: true
      globalMounts:
        - path: /data/
      advancedMounts:
        update:
          glue:
            - path: /etc/xiaoya
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/nfs/pt
      globalMounts:
        - path: /media
          subPath: Cloud
    env-script:
      enabled: true
      type: configMap
      name: scripts
      advancedMounts:
        main:
          init-container:
            - path: /scripts
