app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: nodered/node-red
            tag: 3.1.7-18
          env:
            TZ: Asia/Shanghai
  service:
    main:
      controller: main
      ports:
        http:
          port: 1880
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host node-red.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: node-red-tls-certificate
  persistence:
    config:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
