hajimari:
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host home.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - *host
  hajimari:
    instanceName: null
    defaultEnable: true
    namespaceSelector:
      any: true
    name: HOME
    title: Hajimari
    lightTheme: cloud
    darkTheme: espresso
    customThemes:
      - name: danger
        backgroundColor: '#0c0e0c'
        primaryColor: '#eaebea'
        accentColor: '#d8323c'
    showGreeting: true
    showAppGroups: false
    showAppUrls: false
    showAppInfo: false
    showAppStatus: true
    defaultAppIcon: mdi:application
    showGlobalBookmarks: false
    showBookmarkGroups: true
    alwaysTargetBlank: false
    defaultSearchProvider: Google
    searchProviders:
      - name: Google
        token: g
        icon: simple-icons:google
        searchUrl: https://www.google.com/search?q={query}
        url: https://www.google.com
      - name: DuckDuckGo
        token: d
        icon: simple-icons:duckduckgo
        searchUrl: https://duckduckgo.com/?q={query}
        url: https://duckduckgo.com
      - name: IMDB
        token: i
        icon: simple-icons:imdb
        searchUrl: https://www.imdb.com/find?q={query}
        url: https://www.imdb.com
      - name: Reddit
        token: r
        icon: simple-icons:reddit
        searchUrl: https://www.reddit.com/search?q={query}
        url: https://www.reddit.com
      - name: YouTube
        token: 'y'
        icon: simple-icons:youtube
        searchUrl: https://www.youtube.com/results?search_query={query}
        url: https://www.youtube.com
      - name: Spotify
        token: s
        icon: simple-icons:spotify
        searchUrl: hhttps://open.spotify.com/search/{query}
        url: https://open.spotify.com
    customApps:
      - group: AI
        apps:
          - name: GPT
            url: 'https://chat.openai.com'
            icon: 'mdi:forum'
            info: 'Chat GPT'
          - name: Bing
            url: 'https://www.bing.com/search?q=Bing+AI&showconv=1'
            icon: 'mdi:search-web'
            info: 'New Bing'
    globalBookmarks:
      - group: Movie
        bookmarks:
          - name: jackett
            url: https://jackett.qos.cc
          - name: radarr
            url: https://radarr.qos.cc
          - name: sonarr
            url: https://sonarr.qos.cc
          - name: PT
            url: https://pt.qos.cc
      - group: Managed services
        bookmarks:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com
      - group: Github
        bookmarks:
          - name: Me
            url: https://github.com/retx0
          - name: gists
            url: https://gist.github.com/retX0
  persistence:
    data:
      enabled: false