metal:
  children:
    masters:
      hosts:
        lab: {ansible_host: 172.23.29.3, mac: 'd2:c9:d6:c9:41:01', disk: sda, network_interface: ens18}
#        metal1: {ansible_host: 192.168.1.111, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1}
#        metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
#    workers:
#      hosts:
#       metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
