all:
  vars:
    control_plane_endpoint: arm.qos.cc
    load_balancer_ip_pool:
      - 172.23.29.224/27
metal:
  children:
    masters:
      hosts:
        oracle: {ansible_host: arm.qos.cc, mac: '7c:10:c9:b7:f0:08', disk: nvme0n1, network_interface: enp2s0}
