cloudflared:
  image:
    tag: "2023.5.1"
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.qos.cc'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
