apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snap
  namespace: {{ .Release.Namespace }}
spec:
  cron: "* */12 * * *"
  task: "snapshot"
  retain: 15
  concurrency: 1
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup
  namespace: {{ .Release.Namespace }}
spec:
  cron: "0 4 * * *"
  task: "backup"
  retain: 1
  concurrency: 1
