apiVersion: v2
name: postgresql
version: 0.0.0
dependencies:
- name: postgresql
  version: 13.2.27
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 18.6.2
  repository: https://charts.bitnami.com/bitnami
