longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  persistence:
    # If you have three or more nodes for storage, use 3; otherwise use 2
    defaultClassReplicaCount: 2  # TODO run DR test to see if we actually need 3
    recurringJobSelector:
      enable: true
      jobList:
        '[{"name":"backup","isGroup":false},{"name":"backup","isGroup":false}]'
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/secure-backends: "true"
    hosts:
      - host: &host longhorn.qos.cc
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: &cert longhorn-tls-certificate
        hosts:
          - *host
    tlsSecret: *cert 
    host: *host
