gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.qos.cc
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      APP_NAME: "Let's code."
      database:
        DB_TYPE: postgres
        HOST: database-postgresql.database.svc.cluster.local:5432
        NAME: gitea
        USER: gitea
        PASSWD: gitea
      cache:
        ADAPTER: redis
        HOST: redis://database-redis-headless.database.svc.cluster.local:6379/2?pool_size=100&idle_timeout=180s
      cors:
        ENABLED: true
        ALLOW_DOMAIN: https://*.github.com
      queue:
        TYPE: redis
        CONN_STR: redis://database-redis-headless.database.svc.cluster.local:6379/2
      service:
        DISABLE_REGISTRATION: true
        DEFAULT_USER_VISIBILITY: limited
        DEFAULT_ORG_VISIBILITY: limited
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.qos.cc
      webhook:
        ALLOWED_HOST_LIST: private
      migrations:
        ALLOWED_DOMAINS: gitea.xnxin.com
  persistence:
    storageClass: longhorn
  redis-cluster:
    enabled: false
  postgresql-ha:
    enabled: false
  postgresql:
    enabled: false
