immich:
  image:
    tag: v1.79.1
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          username: immich
          database: immich
          password: immich
  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
  immich:
    persistence:
      library:
        # Automatically creating the library volume is not supported by this chart
        # You have to specify an existing PVC to use
        existingClaim: immich
  microservices:
    enabled: true
    env:
      REVERSE_GEOCODING_DUMP_DIRECTORY: /geodata-cache
    persistence:
      geodata-cache:
        existingClaim: geodata-cache
  machine-learning:
    enabled: true
    persistence:
      cache:
        existingClaim: ml-cache
    resources:
      limits:
        gpu.intel.com/i915: 1
  proxy:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          hajimari.io/enable: 'false'
        hosts:
          - host: &host photos.qos.cc
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host
