immich:
  image:
    tag: v1.123.0
  env:
    DB_VECTOR_EXTENSION: "pgvector"
    REDIS_HOSTNAME: "database-redis-headless.database.svc.cluster.local"
    DB_HOSTNAME: "database-postgresql.database.svc.cluster.local"
    DB_USERNAME: "immich"
    DB_DATABASE_NAME: "immich"
    DB_PASSWORD: "immich"
  postgresql:
    enabled: false
  immich:
    persistence:
      library:
        # Automatically creating the library volume is not supported by this chart
        # You have to specify an existing PVC to use
        existingClaim: immich
  microservices:
    enabled: true
    env:
      REVERSE_GEOCODING_DUMP_DIRECTORY: /geodata-cache
    persistence:
      geodata-cache:
        existingClaim: cache
        subPath: geodata
  machine-learning:
    enabled: true
    securityContext:
      privileged: true
    persistence:
      cache:
        existingClaim: cache
        subPath: machine-learning
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0300_8086.present
              operator: In
              values: [ "true" ]
  server:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host photos.qos.cc
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: immich-tls-certificate
            hosts:
              - *host
