nginx:
  image:
    registry: ghcr.io
    repository: retx0/bitnami-nginx
    tag: main
    pullPolicy: Always
  env:
    TZ: Asia/Shanghai
  ingress:
    hostname: nginx-local.qos.cc
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: 'false'
    tls: true
    extraHosts:
      - name: &pve_host pve.qos.cc
        path: /
    extraTls:
      - secretName: nginx-local-tls
        hosts: 
          - *pve_host
  service:
    type: LoadBalancer
