nginx:
  image:
    registry: ghcr.io
    repository: retx0/bitnami-nginx
  env:
    TZ: Asia/Shanghai
  ingress:
    hostname: nginx-local.qos.cc
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true
    extraHosts:
      - name: &ha ha.qos.cc
      - name: &unifi unifi.qos.cc
      - name: &pve pve.qos.cc
      - name: &emby emby.qos.cc
      - name: &ilo ilo.qos.cc
    extraTls:
      - secretName: nginx-tls
        hosts: 
          # - "*.qos.cc"  NOT recommand this one, it will chaneg DNS * to this nginx, cause other proble.
          - *ha
          - *unifi
          - *pve
          - *emby
          - *ilo
  extraVolumeMounts: # TODO: use template and configmap to generate conf
    - name: conf
      mountPath: /opt/bitnami/nginx/conf/server_blocks/
  extraVolumes:
    - name: conf
      persistentVolumeClaim:
        claimName: config
  networkPolicy:
    enabled: false
  service:
    type: LoadBalancer
  initContainers:
    - name: setup-conf
      image: busybox
      command: ['/bin/sh', '-c']
      args:
        - cd /tmp &&
          wget https://git.qos.cc/api/v1/repos/public/nginx/archive/main.zip &&
          unzip main.zip && cp -rf /tmp/nginx/* /opt/conf
      volumeMounts:
        - name: conf
          mountPath: /opt/conf
