nginx:
  image:
    registry: ghcr.io
    repository: retx0/bitnami-nginx
  env:
    TZ: Asia/Shanghai
  ingress:
    hostname: nginx-local.qos.cc
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true
    extraHosts:
      - name: &ha ha.qos.cc
      - name: &unifi unifi.qos.cc
      - name: &pve pve.qos.cc
      - name: &emby emby.qos.cc
      - name: &ilo ilo.qos.cc
    extraTls:
      # every domain use a single configure.
      # to be banned from let's encrypt
      # do not use wild domain 
      - secretName: ha-tls
        hosts: 
          - *ha
      - secretName: unifi-tls
        hosts: 
          - *unifi
      - secretName: pve-tls
        hosts: 
          - *pve
      - secretName: emby-tls
        hosts: 
          - *emby
      - secretName: ilo-tls
        hosts: 
          - *ilo
  extraVolumeMounts: # TODO: use template and configmap to generate conf
    - name: conf
      mountPath: /opt/bitnami/nginx/conf/server_blocks
    - name: cache
      mountPath: /var/cache/nginx
  extraVolumes:
    - name: conf
      persistentVolumeClaim:
        claimName: config
    - name: cache
      emptyDir:
        sizeLimit: "40Gi"
  networkPolicy:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    type: LoadBalancer
  initContainers:
    - name: setup-conf
      image: busybox
      command: ['/bin/sh', '-c']
      args:
        - cd /tmp &&
          wget https://git.qos.cc/api/v1/repos/public/nginx/archive/main.zip &&
          unzip main.zip && cp -rf /tmp/nginx/* /opt/conf
      volumeMounts:
        - name: conf
          mountPath: /opt/conf
