nginx:
  image:
    registry: ghcr.io
    repository: retx0/bitnami-nginx
  env:
    TZ: Asia/Shanghai
  ingress:
    hostname: nginx-local.qos.cc
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: 'false'
    tls: true
    extraHosts:
      - name: &pve_host pve.qos.cc
        path: /
      - name: &emby_host emby.qos.cc
        path: /
    extraTls:
      - secretName: nginx-tls
        hosts: 
          - *pve_host
          - *emby_host
  extraVolumeMounts:
    - name: conf
      mountPath: /opt/bitnami/nginx/conf/server_blocks/
  extraVolumes:
    - name: conf
      persistentVolumeClaim:
        claimName: config
  networkPolicy:
    enabled: false
  service:
    type: LoadBalancer
  initContainers:
    - name: setup-conf
      image: busybox
      command: ['/bin/sh', '-c']
      args:
        - cd /tmp &&
          wget https://git.qos.cc/api/v1/repos/public/nginx/archive/main.zip &&
          unzip main.zip && cp -rf /tmp/nginx/* /opt/conf
      volumeMounts:
        - name: conf
          mountPath: /opt/conf
