apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitnami-nginx-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: bitnami-nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ha.qos.cc
    - unifi.qos.cc
    - pve.qos.cc
    - emby.qos.cc
    - ilo.qos.cc