# kubectl create secret generic velero \
#   --namespace velero \
#   --from-file cloud=credentials-velero
velero:
  image:
    tag: v1.13.1
  metrics:
    serviceMonitor:
      enabled: true
  initContainers:
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.7.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  nodeAgent:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
  credentials:
    existingSecret: credentials
  configuration:
    backupStorageLocation:
    - name: default
      provider: aws
      bucket: k3s-backup
      default: true
      accessMode: ReadWrite
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: "http://172.23.29.4:9000" # use external minio
    volumeSnapshotLocation:
    - name: default
      provider: aws
      bucket: k3s-snapshots
      config: 
        region: minio
  deployNodeAgent: true
