app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 568
  controllers:
    overseerr:
      containers:
        main:
          image:
            repository: linuxserver/overseerr
            tag: 1.33.2
          env:
            TZ: Asia/Shanghai
    radarr:
      containers:
        main:
          image:
            repository: linuxserver/radarr
            tag: 5.17.2
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
    sonarr:
      containers:
        main:
          image:
            repository: linuxserver/sonarr
            tag: 4.0.12
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
  service:
    overseerr:
      controller: overseerr
      ports:
        http:
          port: 5055
          protocol: HTTP
    radarr:
      controller: radarr
      ports:
        http:
          port: 7878
          protocol: HTTP
    sonarr:
      controller: sonarr
      ports:
        http:
          port: 8989
          protocol: HTTP
  ingress:
    overseerr:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host overseerr.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: overseerr
                port: http
      tls:
        - hosts:
            - *host
          secretName: overseerr-tls-certificate
    radarr:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host radarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: radarr
                port: http
      tls:
        - hosts:
            - *host
          secretName: radarr-tls-certificate
    sonarr:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host sonarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: sonarr
                port: http
      tls:
        - hosts:
            - *host
          secretName: sonarr-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "truenas-iscsi-csi-retain"
      size: 50Gi
      advancedMounts:
        overseerr:
          main:
            - path: /config
              subPath: overseerr
        radarr:
          main:
            - path: /config
              subPath: radarr
        sonarr:
          main:
            - path: /config
              subPath: sonarr
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/nfs/pt
      globalMounts:
        - path: /media
