apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: global-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
    template:
      data:
        PAPERLESS_ADMIN_PASSWORD: "{{ `{{ .admin }}` }}" 
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {"openid_connect": {"APPS": [{"provider_id": "kanidm","name":
          "SSO","client_id": "{{ `{{ .client_id }}` }}","secret":
          "{{ `{{ .client_secret }}` }}","settings": {
          "server_url": "https://auth.qos.cc/oauth2/openid/paperless"}}],
          "OAUTH_PKCE_ENABLED": "True"}}
  data:
  - secretKey: admin
    remoteRef:
      key: paperless.admin
      property: PAPERLESS_ADMIN_PASSWORD
  - secretKey: client_id
    remoteRef:
      key: kanidm.paperless
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: kanidm.paperless
      property: client_secret
