apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: nfs-config2