apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: {{ .Release.Namespace }}-nfs-config