apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.23.29.4
    path: "/mnt/nfs/immich"
  mountOptions:
    - nfsvers=4.2