apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"
  resources:
    requests:
      storage: 4Gi