# Default values for compreface-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  version: 1.2.0
  # MB
  max_upload_size: 1000
  max_request_size: 1000

postgres:
  # db_host: database-postgresql.database
  db_host: 172.23.29.224
  db_name: compreface
  db_port: 5432
  db_user: compreface
  db_password: compreface

core:
  repository: exadel/compreface-core
  port: 3000
  replicas: 1
  name: cf-core

api:
  repository: exadel/compreface-api
  port: 8080
  replicas: 1
  name: cf-api

admin:
  repository: exadel/compreface-admin
  port: 8080
  replicas: 1
  name: cf-admin

fe:
  repository: exadel/compreface-fe
  port: 80
  replicas: 1
  name: cf-fe


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "compreface"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: &host compreface.qos.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: compreface-tls-certificate
      hosts:
        - *host

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
