# kubectl apply -f https://raw.githubusercontent.com/therevoman/edgetpu-device-plugin/master/edgetpu-device-plugin.amd64.yaml
# install intel-gpu-tools first
frigate:
  env:
    TZ: Asia/Shanghai
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Camera
      hajimari.io/icon: cctv
    hosts:
      - host: &host frigate.qos.cc
        paths:
          - '/'
    tls:
      - secretName: frigate-tls-certificate
        hosts:
          - *host
  config: |
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
    mqtt:
      host: 172.23.31.35
      port: 1883
      topic_prefix: frigate
      client_id: frigate
      stats_interval: 60
    cameras:
      door:
        ffmpeg:
          inputs:
            - path: rtsp://172.23.31.40:554/s0
              roles:
                - detect
        detect:
          width: 1920
          height: 1080
          fps: 10
      door2:
        ffmpeg:
          inputs:
            - path: rtsp://172.23.31.41:554/stream1
              roles:
                - detect
        detect:
          width: 2034
          height: 1296
          fps: 10
    record:
      enabled: True
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects
  extraVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nfs-frigate
  extraVolumeMounts:
    - name: media
      mountPath: /media
  securityContext:
    privileged: true
    capabilities:
        add: ["CAP_PERFMON"]
  resources:
    limits:
      kkohtaka.org/edgetpu: 1
      gpu.intel.com/i915: 1

double-take:
  image:
    repository: ghcr.io/skrashevich/double-take
    tag: v1.13.11.9rc2
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host double-take.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: double-take-tls-certificate
          hosts:
            - *host
  config:
    mqtt:
      host: 172.23.31.35
      port: 1883
    frigate:
      url: http://frigate:5000
    detectors:
      compreface:
        enabled: true
        url: http://compreface-api:8080
        key: 36df6225-b0bd-4d82-916e-1008414fa801
    cameras:
      door:	
        masks:	
          coordinates:	
            - 1920,0,1920,328,1638,305,1646,0	
          size: 1920x1080
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4G
      storageClass: longhorn

compreface:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host compreface.qos.cc
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: compreface-tls-certificate
        hosts:
          - *host