apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: nfs-downloads