app-template:
  defaultPodOptions:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0300_8086.present
              operator: In
              values: [ "true" ]
    securityContext:
      fsGroup: 568
  controllers:
    main:
      containers:
        main:
          image:
            repository: allanpk716/chinesesubfinder
            tag: v0.55.3
          env:
            PUID: 2199
            PGID: 568
            TZ: Asia/Shanghai
            UMASK: 022
            PERMS: false
          securityContext:
            privileged: true
  service:
    main:
      controller: main
      ports:
        http:
          port: 19035
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host subfinder.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: subfinder-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: "truenas-iscsi-csi-retain"
      size: 20Gi
      globalMounts:
        - path: /config
    graphic:
      type: hostPath
      hostPath: "/dev/dri"
      globalMounts:
        - path: "/dev/dri"
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/nfs/pt
      globalMounts:
        - path: /media
