app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 568
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0300_8086.present
              operator: In
              values: [ "true" ]
  controllers:
    main:
      pod:
        hostNetwork: true  # 将hostNetwork移到这里
      containers:
        main:
          image:
            repository: ghcr.io/koush/scrypted
            tag: v0.114.0-jammy-full
          env:
            TZ: Asia/Shanghai
          securityContext:
            privileged: true
            capabilities:
              add: ["CAP_PERFMON", "NET_BIND_SERVICE"]
  service:
    main:
      controller: main
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ports:
        http:
          port: 11080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host nvr.qos.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: nvr-tls-certificate
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /server/volume
    media:
      enabled: true
      type: nfs
      server: 172.23.29.4
      path: /mnt/wd-disk/NVR
      globalMounts:
        - path: /nvr
