apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: postgresql-auth
  data:
    - secretKey: adminPassword
      remoteRef:
        key: postgresql
        property: auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: mysql-auth
  data:
    - secretKey: mysql-password
      remoteRef:
        key: mysql
        property: pwd
    - secretKey: mysql-replication-password
      remoteRef:
        key: mysql
        property: replication
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql
        property: root