apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: adminPassword
      remoteRef:
        key: postgresql.auth
        property: adminPassword
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: mysql-password
      remoteRef:
        key: mysql.pwd
        property: password
    - secretKey: mysql-replication-password
      remoteRef:
        key: mysql.replication
        property: replication-password
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql.root
        property: root-password