# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Database.postgresql
- name: postgresql
  data:
    - key: auth
      length: 32
      special: false
# Database.mysql
- name: mysql
  data:
    - key: root
      length: 32
      special: false
    - key: pwd
      length: 32
      special: false
    - key: replication
      length: 32
      special: false

# vaultwarden
- name: vaultwarden.admin
  data:
    - key: token
      length: 32
      special: false