# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Database.postgresql
- name: postgresql.auth
  data:
    - key: secret
      length: 32
      special: false
# Database.mysql
- name: mysql.root
  data:
    - key: secret
      length: 32
      special: false
- name: mysql.pwd
  data:
    - key: secret
      length: 32
      special: false
- name: mysql.replication
  data:
    - key: secret
      length: 32
      special: false
