apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 2G