apiVersion: v1
kind: Service
metadata:
  name: {{ include "video.fullname" . }}
  labels:
    {{- include "video.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: discovery
      port: 10001
      protocol: UDP
    - name: rtmp
      port: 1935
      protocol: TCP
    - name: rtmps
      port: 7444
      protocol: TCP
    - name: rtsp
      port: 7447
      protocol: TCP
    - name: rtsp-udp
      port: 7447
      protocol: UDP
    - name: camera-in
      port: 6666
      protocol: TCP
    - name: management
      port: 7442
      protocol: TCP
    - name: talkback
      port: 7004
      protocol: UDP
    - name: http
      port: 7080
      protocol: TCP
    - name: https
      port: 7443
      protocol: TCP
    - name: video-over-http
      port: 7445
      protocol: TCP
    - name: video-over-https
      port: 7446
      protocol: TCP
  selector:
    {{- include "video.selectorLabels" . | nindent 4 }}