apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-config
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: secret.json
      remoteRef:
        key: n8n.config
        property: secret