# see https://velero.io/docs/v1.13/api-types/schedule/
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-bakcup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: 0 3 * * *
  template:
    includedNamespaces:
    - '*'
    excludedNamespaces:
    - 'nginx'
    includedResources:
    - '*'
    includeClusterResources: true
    snapshotVolumes: null
    storageLocation: default
    volumeSnapshotLocations:
      - default
    ttl: 1024h0m0s
    defaultVolumesToFsBackup: true
status:
  phase: "FailedValidation"
  lastBackup:
  validationErrors:
    - >-
      a BackupStorageLocation CRD with the name specified in the backup spec
      needs to be created before this backup can be executed. Error:
      backupstoragelocation.velero.io "aws" not found
      