apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: global-secrets
    kind: ClusterSecretStore
  target:
    name: credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id="{{ `{{ .KEY_ID }}` }}"
          aws_secret_access_key="{{ `{{ .ACCESS_KEY }}` }}"
  data:
  - secretKey: KEY_ID
    remoteRef:
      key: velero.credential
      property: key_id
  - secretKey: ACCESS_KEY
    remoteRef:
      key: velero.credential
      property: access_key
