apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: {{ .Release.Namespace }}
data:
  setup-env.sh: |-
    #!/bin/sh

    if [ ! -f "/data/docker_address.txt" ]; then
        echo "https://xiaoya.qos.cc" > /data/docker_address.txt
        echo "write into /data/docker_address.txt"
    fi

    if [ ! -f "/data/myopentoken.txt" ]; then
        echo "$OPEN_TOKEN" > /data/myopentoken.txt
        echo "write into /data/myopentoken.txt"
    fi

    if [ ! -f "/data/temp_transfer_folder_id.txt" ]; then
        echo "$FOLDER_ID" > /data/temp_transfer_folder_id.txt
        echo "write into /data/temp_transfer_folder_id.txt"
    fi
