apiVersion: batch/v1
kind: CronJob
metadata:
  name: xiaoya-update
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '0 2 */9 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-meta-info
            image: xiaoyaliu/glue
            imagePullPolicy: Always
            command: ['/update.sh']
            env:
              - name: LANG
                value: C.UTF-8
            volumeMounts:
              - name: xiaoya-data
                mountPath: /etc/xiaoya
                subPath: xiaoya
              - name: media
                mountPath: /media
                subPath: Cloud
          restartPolicy: Never
          volumes:
            - name: xiaoya-data
              persistentVolumeClaim:
                claimName: pvc-config
            - name: media
              persistentVolumeClaim:
                claimName: nfs-downloads
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aliyun-temp-folder-clear
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '0 3 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clean
            image: curlimages/curl
            command: ['/bin/sh', '-c']
            args:
              - sh <(curl -s https://git.qos.cc/public/aliyun_clear/raw/branch/main/clear.sh)
            volumeMounts:
              - name: xiaoya-data
                mountPath: /data
                subPath: xiaoya
          restartPolicy: Never
          volumes:
            - name: xiaoya-data
              persistentVolumeClaim:
                claimName: pvc-config