apiVersion: batch/v1
kind: CronJob
metadata:
  name: xiaoya-update
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '0 4 */3 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-meta-info
            image: xiaoyaliu/glue
            imagePullPolicy: Always
            command: ['/update.sh']
            env:
              - name: LANG
                value: C.UTF-8
            volumeMounts:
              - name: xiaoya-data
                mountPath: /etc/xiaoya
                subPath: xiaoya
              - name: media
                mountPath: /media
                subPath: Cloud
          restartPolicy: Never
          volumes:
            - name: xiaoya-data
              persistentVolumeClaim:
                claimName: pvc-config
            - name: media
              persistentVolumeClaim:
                claimName: nfs-downloads