apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-nfs-downloads
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.23.29.4
    path: "/mnt/nfs/pt"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-nfs-config
spec:
  capacity:
    storage: 230Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.23.29.4
    path: "/mnt/nfs/docker"
  mountOptions:
    - nfsvers=4.2