apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: {{ .Release.Namespace }}-nfs-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 230Gi
  volumeName: {{ .Release.Namespace }}-nfs-config