apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xiaoya-token
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: open_token
      remoteRef:
        key: alist
        property: open-token
    - secretKey: folder-id
      remoteRef:
        key: alist
        property: dir-id
    - secretKey: token
      remoteRef:
        key: alist
        property: token
