apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xiaoya-token
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: open_token
      remoteRef:
        key: /alist/
        property: open_token
    - secretKey: folder-id
      remoteRef:
        key: /alist/
        property: xiaoya_folder_id
    - secretKey: token
      remoteRef:
        key: /alist/
        property: token
