apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.23.31.4
    path: "/mnt/nfs/pt"
  mountOptions:
    - nfsvers=4.2
