apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: emby-media
