ingress-nginx:
  controller:
    config:
      proxy-body-size: "0"
      allow-snippet-annotations: true
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    636: kanidm/kanidm:636
