apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core
  name: {{ .Values.core.name }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Values.core.name }}
          image: {{ .Values.core.repository }}:{{ .Values.app.version }}-mobilenet
          ports:
            - containerPort: {{ .Values.core.port }}
          env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
      restartPolicy: Always