apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: {{ .Values.fe.name }}
spec:
  replicas: {{ .Values.fe.replicas }}
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Values.fe.name }}
          image: '{{ .Values.fe.repository }}:{{ .Values.app.version }}'
          ports:
            - containerPort: {{ .Values.fe.port }}
          env:
            - name: CLIENT_MAX_BODY_SIZE
              value: '{{ .Values.app.max_upload_size }}m'
            - name: PROXY_READ_TIMEOUT
              value: '30'
            - name: PROXY_CONNECT_TIMEOUT
              value: '30'
      restartPolicy: Always