apiVersion: v1
kind: Service
metadata:
  name: compreface-core
spec:
  type: ClusterIP
  selector:
      app: core
  ports:
  - port: {{ .Values.core.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-api
spec:
  type: ClusterIP
  selector:
      app: api
  ports:
  - port: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-admin
spec:
  type: ClusterIP
  selector:
      app: admin
  ports:
  - port: {{ .Values.admin.port }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe
  name: compreface-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.fe.port }}
  selector:
    app: fe