qbittorrent:
  env:
    PUID: 2199
    PGID: 568
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: 'false'
      hosts:
        - host: &host pt.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: pt-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
      retain: true

    downloads:
      enabled: true
      mountPath: /downloads
      existingClaim: nfs-downloads
sonarr:
  env:
    PUID: 2199
    PGID: 568
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/group: ""
        hajimari.io/icon: "television"
      hosts:
        - host: &host sonarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
      retain: true

    media:
      enabled: true
      mountPath: /media
      existingClaim: nfs-downloads
radarr:
  env:
    PUID: 2199
    PGID: 568
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/group: ""
        hajimari.io/icon: "movie"
      hosts:
        - host: &host radarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /config
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
      retain: true
    media:
      enabled: true
      mountPath: /media
      existingClaim: nfs-downloads

