qbittorrent:
  image: 
    tag: "4.6.2"
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host pt.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: pt-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 2199
    runAsGroup: 568
  persistence:
    config:
      enabled: true
      mountPath: /config
      subPath: qbittorrent
      existingClaim: config
      retain: true
    downloads:
      enabled: true
      mountPath: /downloads
      existingClaim: nfs-downloads
  service:
    main:
      type: LoadBalancer
    bittorrent:
      enabled: true
      type: LoadBalancer
  resources:
    limits:
      memory: 2Gi
overseerr:
  image:
    tag: 1.33.2 
  env:
    PUID: 2199
    PGID: 568
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host overseerr.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: overseerr-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      mountPath: /app/config
      subPath: overseerr
      existingClaim: config
sonarr:
  image:
    tag: 4.0.2
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host sonarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 2199
    runAsGroup: 568
  persistence:
    config:
      enabled: true
      mountPath: /config
      subPath: sonarr
      existingClaim: config
      retain: true
    media:
      enabled: true
      mountPath: /media
      existingClaim: nfs-downloads
radarr:
  image:
    tag: 5.3.6.8612
  env:
    TZ: Asia/Shanghai
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host radarr.qos.cc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *host
  podSecurityContext:
    runAsUser: 2199
    runAsGroup: 568
  persistence:
    config:
      enabled: true
      mountPath: /config
      subPath: radarr
      existingClaim: config
      retain: true
    media:
      enabled: true
      mountPath: /media
      existingClaim: nfs-downloads
